/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import DrawUI from "./JJExport/View/DrawUI"
import AutoFixPosY from "./JJExport/Libs/AutoFixPosY"
import FinishGameUI from "./JJExport/View/FinishGameUI"
import FriendGameUI from "./JJExport/View/FriendGameUI"
import FixNodeY from "./Libs/FixNodeY"
import FullGameUI from "./JJExport/View/FullGameUI"
import ProgramUI from "./JJExport/View/ProgramUI"
import RecommendUI from "./JJExport/View/RecommendUI"
import ScrollUI from "./JJExport/View/ScrollUI"
import StartNavUI from "./JJExport/View/StartNavUI"
import WeChatUI from "./JJExport/View/WeChatUI"
import FinishUI from "./View/FinishUI"
import GameUI from "./View/GameUI"
import LoadingUI from "./View/LoadingUI"
import MadUI from "./View/MadUI"
import StartUI from "./View/StartUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MyScenes/StartUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("JJExport/View/DrawUI.ts",DrawUI);
        reg("JJExport/Libs/AutoFixPosY.ts",AutoFixPosY);
        reg("JJExport/View/FinishGameUI.ts",FinishGameUI);
        reg("JJExport/View/FriendGameUI.ts",FriendGameUI);
        reg("Libs/FixNodeY.ts",FixNodeY);
        reg("JJExport/View/FullGameUI.ts",FullGameUI);
        reg("JJExport/View/ProgramUI.ts",ProgramUI);
        reg("JJExport/View/RecommendUI.ts",RecommendUI);
        reg("JJExport/View/ScrollUI.ts",ScrollUI);
        reg("JJExport/View/StartNavUI.ts",StartNavUI);
        reg("JJExport/View/WeChatUI.ts",WeChatUI);
        reg("View/FinishUI.ts",FinishUI);
        reg("View/GameUI.ts",GameUI);
        reg("View/LoadingUI.ts",LoadingUI);
        reg("View/MadUI.ts",MadUI);
        reg("View/StartUI.ts",StartUI);
    }
}
GameConfig.init();